// Generated by CoffeeScript 1.3.3
(function() {
  var nonAsyncCount, root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  "use strict";


  nonAsyncCount = 0;

  root.asyncExecute = function(fn) {
    if ((typeof document !== "undefined" && document !== null) && (document.hidden || document.mozHidden || document.webkitHidden || document.msHidden) && nonAsyncCount++ < 10000) {
      return fn();
    } else {
      nonAsyncCount = 0;
      return setTimeout(fn, 0);
    }
  };

}).call(this);
